import * as THREE from 'three';
import type { TwinState, WorldSnapshot } from '../../../src/core/types.js';

export class WorldRenderer {
 private objects=new Map<string,THREE.Object3D>();
 constructor(private scene:THREE.Scene){}
 sync(snapshot:WorldSnapshot){const alive=new Set<string>();for(const twin of snapshot.twins){alive.add(twin.id);let o=this.objects.get(twin.id);if(!o){o=this.create(twin);this.objects.set(twin.id,o);this.scene.add(o)}this.update(o,twin)}for(const [id,o] of this.objects)if(!alive.has(id)){this.scene.remove(o);this.objects.delete(id)}}
 private create(t:TwinState):THREE.Object3D{let mesh:THREE.Mesh;const mat=(c:number)=>new THREE.MeshStandardMaterial({color:c,roughness:.55,metalness:.25});switch(t.kind){case'tank':mesh=new THREE.Mesh(new THREE.CylinderGeometry(2,2,4,32),mat(0x6f7f8f));break;case'pipe':mesh=new THREE.Mesh(new THREE.CylinderGeometry(.22,.22,8,16),mat(0x89939d));mesh.rotation.z=Math.PI/2;break;case'wall':mesh=new THREE.Mesh(new THREE.BoxGeometry(8,4,.3),mat(0x56616a));break;case'ignition':mesh=new THREE.Mesh(new THREE.BoxGeometry(.8,.8,.8),mat(0xd6b34a));break;case'release':mesh=new THREE.Mesh(new THREE.SphereGeometry(1,20,16),new THREE.MeshStandardMaterial({color:0x8ec5cf,transparent:true,opacity:.18,depthWrite:false}));break;case'fire':mesh=new THREE.Mesh(new THREE.SphereGeometry(1,24,20),new THREE.MeshStandardMaterial({color:0xff6a16,emissive:0xff2500,emissiveIntensity:2,transparent:true,opacity:.82}));break;default:mesh=new THREE.Mesh(new THREE.BoxGeometry(.5,.5,.5),mat(0x667788))}mesh.name=t.id;mesh.userData.twinId=t.id;return mesh}
 private update(o:THREE.Object3D,t:TwinState){o.position.set(t.position.x,t.position.y,t.position.z);o.visible=t.active||t.kind==='tank';if(t.kind==='release'){const r=Number(t.metadata.radiusM??1);o.scale.setScalar(Math.max(.25,r))}if(t.kind==='fire'){const mw=Number(t.metadata.intensityMw??1);o.scale.set(1+mw*.12,1.3+mw*.18,1+mw*.12)}if(t.kind==='tank'||t.kind==='wall'||t.kind==='pipe'){const mesh=o as THREE.Mesh;const m=mesh.material as THREE.MeshStandardMaterial;const heat=Math.min(1,Math.max(0,(t.temperatureK-303)/250));m.emissive.setRGB(heat*.55,heat*.08,0);m.emissiveIntensity=heat*2;if(t.integrity<.7)o.rotation.z=(1-t.integrity)*.12}}
 getObject(id:string){return this.objects.get(id)}
}
